addSbtPlugin("com.timushev.sbt"          % "sbt-updates"   % "0.5.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.0")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"    % "3.3.0")
addSbtPlugin("org.foundweekends"         % "sbt-bintray"   % "0.5.4")
addSbtPlugin("org.scoverage"             % "sbt-scoverage" % "1.6.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.11")
