addSbtPlugin("com.timushev.sbt"          % "sbt-updates"    % "0.6.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.4.6")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "1.9.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.20")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release" % "1.5.10")
