addSbtPlugin("com.timushev.sbt" % "sbt-updates"    % "0.7.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"   % "2.6.1")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"  % "2.4.4")
addSbtPlugin("org.typelevel"    % "sbt-tpolecat"   % "0.5.7")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release" % "1.12.0")
